
  var questions = {
    "level" : "ez",
    "category" : "sports",
    "question": "Which NBA coach coined the term “three-peat”?",
    "answerA" : "Pat Riley",
    "answerB" : "Phil Jackson",
    "answerC" : "Byron Scott",
    "answerD" : "Greg Popovich",
    "correct" : "answerA"
  };
  },
  "qtwo" : {
    "level" : "ez",
    "category" : "sports",
    "question" : "How many NFL teams does California have?",
    "answerA" : "1",
    "answerB" : "3",
    "answerC" : "5",
    "answerD" : "4",
    "correct" : "answerD",
  },
  "qthree" : {
    "level" : "ez",
    "category" : "sports",
    "question" : "Which team won the World Cup in 2014",
    "answerA" : "Brazil",
    "answerB" : "USA",
    "answerC" : "Germany",
    "answerD" : "U.K.",
    "correct" : "answerC",
  },
  "qfour" : {
    "level" : "med",
    "category" : "sports",
    "question" : "Who is Baseball's all-time hits leader with 4,256?",
    "answerA" : "Babe Ruth",
    "answerB" : "Pete Rose",
    "answerC" : "Barry Bonds",
    "answerD" : "Hank Aaron",
    "correct" : "answerB",
  },
  "5" : {
    "level" : "med",
    "category" : "sports",
    "question" : "Which city in Ohio has the NFL hall of fame and is the site of the annual preseason \"hall of fame game\"",
    "answerA" : "Scranton",
    "answerB" : "Canton",
    "answerC" : "Cooperstown",
    "answerD" : "Cleveland",
    "correct" : "answerB",
  },
  "qsix" : {
    "level" : "med",
    "category" : "sports",
    "question" : "How many championships did Michael Jordan and Phil Jackson win together on the Bulls?",
    "answerA" : "4",
    "answerB" : "5",
    "answerC" : "6",
    "answerD" : "11",
    "correct" : "answerC",
  },
  "7" : {
    "level" : "hard",
    "category" : "sports",
    "question" : "Which NCAA Basketball coach has the most championships with 12?",
    "answerA" : "Mike Krzyzewski (Coach K)",
    "answerB" : "Bobby Knight",
    "answerC" : "John Madden",
    "answerD" : "John Wooden",
    "correct" : "answerD",
  },
  "8" : {
    "level" : "hard",
    "category" : "sports",
    "question" : "Who has won the PGA Player of the Year Award a record setting 11 times?",
    "answerA" : "Jack Nicklaus",
    "answerB" : "Rory Mcilroy",
    "answerC" : "Arnold Palmer",
    "answerD" : "Tiger Woods",
    "correct" : "answerD",
  },
  "9" : {
    "level" : "hard",
    "category" : "sports",
    "question" : "Jules Bianchi was recently killed in a Formula One race, his death has been the first in Formula One since this movie-inspiring story of a Brazillian in 1994 featuring: ",
    "answerA" : "Mario Andretti",
    "answerB" : "Ayrton Sena",
    "answerC" : "Michael Schumaker",
    "answerD" : "Niki Lauda",
    "correct" : "answerB",
  },
  "10" : {
    "level" : "hard",
    "category" : "sports",
    "question" : "At which college did Peyton Manning play football?",
    "answerA" : "Georgia",
    "answerB" : "Florida",
    "answerC" : "USC",
    "answerD" : "Tennessee",
    "correct" : "answerD",
  },
{
    "level" : "ez",
    "category" : "ww2",
    "question" : "What is the name of the still visible sunken U.S. battleship that accounted for almost half the casualties at Pearl Harbor?",
    "answerA" : "U.S.S. Arizona",
    "answerB" : "U.S.S. Constitution",
    "answerC" : "U.S.S. Nevada",
    "answerD" : "U.S.S. Califonia",
    "correct" : "answerA",
  },
{
    "level" : "ez",
    "category" : "ww2",
    "question" : "What was the name given to the alliance between Adolph Hitler, Benito Mussolini, and Emperor Hirohito in World War II?",
    "answerA" : "Alliance of evil",
    "answerB" : "Axis of evil",
    "answerC" : "Angels of evil",
    "answerD" : "Allied Forces",
    "correct" : "answerB",
  },
{
    "level" : "ez",
    "category" : "ww2",
    "question" : "\"D-Day\" or \"“Operation Overlord\" occurred on the beaches of Normandy in what country?",
    "answerA" : "France",
    "answerB" : "U.K.",
    "answerC" : "Netherlands",
    "answerD" : "Germany",
    "correct" : "answerA",
  },
{
    "level" : "med",
    "category" : "ww2",
    "question" : "Which of these World War II beligerants was estimated to have more tanks than the rest of the world combined?",
    "answerA" : "USA",
    "answerB" : "Russia",
    "answerC" : "Germany",
    "answerD" : "China",
    "correct" : "answerB",
  },
{
      "level" : "med",
    "category" : "ww2",
    "question" : "All of these were bloody LAND battles of the Pacific Theater except:",
    "answerA" : "Guadalcanal",
    "answerB" : "Midway",
    "answerC" : "Peleliu",
    "answerD" : "Iwo Jima",
    "correct" : "answerB",
  },
{
    "level" : "med",
    "category" : "ww2",
    "question" : "Germany's invasion or \"Anschluss\" of what country caused France and Britain to join the war?",
    "answerA" : "Poland",
    "answerB" : "Austria",
    "answerC" : "Hungary",
    "answerD" : "Czechoslovakia",
    "correct" : "answerA",
  },
{
      "level" : "med",
    "category" : "ww2",
    "question" : "This palacial hilltop estate was once thought to be Hitler's personal retreat:",
    "answerA" : "Dragon's Den",
    "answerB" : "Eidelweiss Retreat",
    "answerC" : "Lion's Gate",
    "answerD" : "Eagle's Nest",
    "correct" : "answerD",
  },
{
    "level" : "hard",
    "category" : "ww2",
    "question" : "The invasion of the U.S.S.R. by Germany was named Operation _____:",
    "answerA" : "Market Garden",
    "answerB" : "Overlord",
    "answerC" : "Uranus",
    "answerD" : "Zauberflöte",
    "correct" : "answerB",
  },
  "19" : {
    "level" : "hard",
    "category" : "ww2",
    "question" : " The U.S. Navy lost 4 aircraft carriers (CV Class) in 1942 (and total during the war), they were the: U.S.S. Yorktown, U.S.S. Lexington, U.S.S. Hornet and:",
    "answerA" : "U.S.S. Concord",
    "answerB" : "U.S.S. Stinger",
    "answerC" : "U.S.S. Essex",
    "answerD" : "U.S.S. Wasp",
    "correct" : "answerD",
  },
  "20" : {
    "level" : "hard",
    "category" : "ww2",
    "question" : "This major U.S. Battle in the area now known as Benelux had 89,500 total casualties, more than Guadalcanal and Normandy combined:",
    "answerA" : "Battle of Britain",
    "answerB" : "Battle of Okinawa",
    "answerC" : "Battle of the Bulge",
    "answerD" : "Battle of Stalingrad",
    "correct" : "answerC",
  },
  !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!{
    "level" : "ez",
    "category" : "music",
    "question" : "In 2011, which female artist sold 25 million copies of her hit album \"21\"",
    "answerA" : "Taylor Swift",
    "answerB" : "Adele",
    "answerC" : "Beyonce",
    "answerD" : "Brittney Spears",
    "correct" : "answerB"
  },
  {
    "level" : "ez",
    "category" : "music",
    "question" : "In 1979 Charlie Daniels released his famous track about a fiddle playing contest with the devil called the Devil went down to ____",
    "answerA" : "Florida",
    "answerB" : "Georgia",
    "answerC" : "Mississippi",
    "answerD" : "Harlem",
    "correct" : "answerB",
  },
  {
    "level" : "ez",
    "category" : "music",
    "question" : " What legendary US festival that hosted over 350,000 fans took place in 1969 in New York and has had tributary events every ten years since?",
    "answerA" : "Gunstock",
    "answerB" : "The Vans Warped Tour",
    "answerC" : "Ozzfest",
    "answerD" : "Woodstock",
    "correct" : "answerD"
  },
  {
    "level" : "med",
    "category" : "music",
    "question" : "Who has made 3 albums that have sold 30 million or more, including an album that sold an estimated 46 million copies (the highest of all time)",
    "answerA" : "Paul McCartney",
    "answerB" : "Bob Dylan",
    "answerC" : "Michael Jackson",
    "answerD" : "Garth Brooks",
    "correct" : "answerC"
  },
  {
    "level" : "med",
    "category" : "music",
    "question" : "Who played bass guitar for The Beatles?",
    "answerA" : "John",
    "answerB" : "Paul",
    "answerC" : "Ringo",
    "answerD" : "George",
    "correct" : "answerA"
  },
   {
    "level" : "med",
    "category" : "music",
    "question" : "Which long haired musician would famously do anything for love (but he won’t do that)?",
    "answerA" : "Meat Loaf",
    "answerB" : "Bruce Springsteen",
    "answerC" : "Billy Joel",
    "answerD" : "John Lennon",
    "correct" : "answerA"
  },
  {
    "level" : "med",
    "category" : "music",
    "question" : "What arcade game did the main character of the 1969 rock opera \"Tommy\" play exceedingly well desipite his physical limitations?",
    "answerA" : "Foosball",
    "answerB" : "Ping Pong",
    "answerC" : "Mario Brothers",
    "answerD" : "Pinball",
    "correct" : "answerD",
  },
  {
    "level" : "hard",
    "category" : "music",
    "question" : "How many total keys are on most modern pianos?",
    "answerA" : "88",
    "answerB" : "80",
    "answerC" : "98",
    "answerD" : "89",
    "correct" : "answerA",
  },
  {
    "level" : "hard",
    "category" : "music",
    "question" : "This European band has received 22 Grammy Awards out of 25 nominations, their last one in 2006 for the song \"City of Blinding Lights\"",
    "answerA" : "The Rolling Stones",
    "answerB" : "U2",
    "answerC" : "The Beatles",
    "answerD" : "Elton John",
    "correct" : "answerB",
  },
  {
    "level" : "hard",
    "category" : "music",
    "question" : "What famous musician was killed in 1980 by a man named Mark David Chapman?",
    "answerA" : "Andy Kaufman",
    "answerB" : "Eazy-E",
    "answerC" : "Frank Zappa",
    "answerD" : "John Lennon",
    "correct" : "answerD",
  },
  "31" : {
    "level" : "ez",
    "category" : "ushistory",
    "question" : "What was the last state to be admitted to the union in 1959?",
    "answerA" : "Alaska",
    "answerB" : "Hawaii",
    "answerC" : "Puerto Rico",
    "answerD" : "Guam",
    "correct" : "answerB",
  },
  "32" : {
    "level" : "ez",
    "category" : "ushistory",
    "question" : "Who is the signature author on the Declaration of Independence?",
    "answerA" : "George Washington",
    "answerB" : "Benjamin Franklin",
    "answerC" : "Thomas Jefferson",
    "answerD" : "Alexander Hamilton",
    "correct" : "answerC",
  },
  "33" : {
    "level" : "ez",
    "category" : "ushistory",
    "question" : "Which of these states is NOT a member of the 13 original colonies",
    "answerA" : "New Jersey",
    "answerB" : "Vermont",
    "answerC" : "New York",
    "answerD" : "Virginia",
    "correct" : "answerB",
  },
  "34" : {
    "level" : "med",
    "category" : "ushistory",
    "question" : "During which war did British forces invade Washington D.C. and burn the White House?",
    "answerA" : "French-Indian War",
    "answerB" : "War of 1812",
    "answerC" : "Civil War",
    "answerD" : "Revolutionary War",
    "correct" : "answerB",
  }

};
